### ISSUE TITLE
Crop mask stays present with zero-size crop

### ISSUE THREAD

**Issue by henrywoody** [sekoyo/react-image-crop#575]
After creating a crop selection and then clicking on the crop area to clear the crop, the crop goes away but the background mask stays visible.

In a0cc2a1ea1508be48457452899b2783c591732e7, the crop mask was separated from the crop selection as a separate HTML element, but the styles were not updated.

**Comment by sekoyo** [comment]
I published your commit in 11.0.5 please try that
