### ISSUE TITLE
mask does not fully cover the image when the image to a smaller aspect ratio

### ISSUE THREAD

**Issue by kaidev1024** [sekoyo/react-image-crop#581]
I tried to create a component for image cropping, part of which looks like the code below. It works fine for image cropping. But when I tried to change the image from 1:1 aspect ration to 9:16, the mask only covers the upper part with a square. The lower part is not covered as shown in the image. Is there any way to fix that? Thanks!
```
<>
<div>
        <ReactCrop
          crop={crop}
          onChange={func}
          circularCrop={circularCrop}
          aspect={aspectRatio}
          minWidth={MIN_DIMENSION}
          keepSelection
        >
          <img
          />
        </ReactCrop>
</div>
<input
          id="imageInput"
          type="file"
          accept="image/*"
        />
<>
```
<img width="457" alt="Screenshot 2024-02-24 at 10 28 10 PM" src="https://github.com/sekoyo/react-image-crop/assets/58545754/525025cf-fa1d-4958-847b-1eb59cad9a95">

**Comment by sekoyo** [comment]
Are you able to repro the issue on https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o ?

**Comment by kaidev1024** [comment]
it works fine with your code. I need to do some debugging on my end. Thanks!
