### ISSUE TITLE
 iPhone 15's 24 MP (res 4284 X 5712) image resolution is making the image black after cropping.

### ISSUE THREAD

**Issue by vibhavawasthi** [sekoyo/react-image-crop#588]
We need to accommodate iPhone 15's 24 MP (res 4284 X 5712) image resolution as well, to make it work properly, kindly make the updates for the same.

**Comment by sekoyo** [comment]
This library doesn’t have code to crop the image just a simple example. You can look online how to resize canvas images in a way that suits you (or do it on a server)
