### ISSUE TITLE
Problems when importing from react image crop using moduleResolution: "nodenext" in tsconfig.json

### ISSUE THREAD

**Issue by alvarogfn** [sekoyo/react-image-crop#601]
I'm building a component library, and I've encountered problems importing react-image-crop when using NodeNext module resolution. Can anyone help me find a solution?

![image](https://github.com/user-attachments/assets/9422d939-7696-45a7-9150-4bc9eee59cf4)

I uploaded a version with the problem on Stackblitz:
https://stackblitz.com/edit/react-image-crop-node-next?file=src%2FApp.tsx

**Comment by alvarogfn** [comment]
I was able to resolve this problem by making this change:
![image](https://github.com/user-attachments/assets/ddc79f15-0644-4859-8562-fd477e0bd07c)
I'll make a local patch, thanks!

**Comment by sekoyo** [comment]
Fixed via https://github.com/sekoyo/react-image-crop/pull/602 in 11.0.7
